### ISSUE TITLE
key is not valid - MacOS & Windows Client

### ISSUE THREAD

**Issue by insta-ruv** [cloudfieldcz/shieldoo-mesh-docs#23]
### Question

What key is invalid when the shieldoo-mesh-admin container shows the following in the trace logs?

time="2023-11-11T12:52:13Z" level=debug msg="useraccess afterfind"
time="2023-11-11T12:52:13Z" level=debug msg="key is not valid"
time="2023-11-11T12:52:13Z" level=debug msg="key is not valid -> key: *********"
time="2023-11-11T12:52:13Z" level=debug msg="key is not valid -> keymaterial: ********"
time="2023-11-11T12:52:13Z" level=debug msg="key is not valid -> lockey: ********"

### Additional Info
I've set up the repo and compose file, set up the AzureAD IDs and secret in the .env file.
I can successfully reach the admin UI after running the docker containers as well as join servers to the network with successful routing. The only part that does not work is setting up the clients on the computer.

On MacOS and Windows, when completing the AzureAD authentication I receive the message "Now you can close your browser and go back to your application."
The client tries to connect but the trace level logs in the shieldoo-mesh-admin container only shows the logs above.

The logs on MacOS shows:
time="2023-11-11T14:52:12+02:00" level=info msg="servicecheck - ping started"
time="2023-11-11T14:52:13+02:00" level=info msg="Login  to management server: https://admin.mydomain.com/api/oauth/authorize"

The admin security logs show the following after signing in on the client app:
`{
    "UPN": "myuser@mydomain.com",
    "Entity": "",
    "LogType": "userdevicelogin",
    "Message": "User Device login success, access token returned.",
    "Timestamp": "2023-11-11T12:50:43.270095903Z",
    "CurrentObject": null,
    "OriginalObject": null
}`
'{
    "UPN": "myuser@mydomain.com",
    "Entity": "",
    "LogType": "devicelogin",
    "Message": "Device login success, JWT token generated.",
    "Timestamp": "2023-11-11T12:50:43.304698649Z",
    "CurrentObject": null,
    "OriginalObject": null
}'

It is never able to connect.
I have also tested the iOS client which does work, and I can communicate with servers.
Everything works except I cannot get past the invalid key message on MacOS or Windows.
Making sure to prune docker and delete the Postgres DB, I've reinstalled multiple times with default tokens, CAs and secrets as well as generating custom keys, secrets, and tokens, yet all result in the same error in the logs - "key is not valid".

**Comment by valda-z** [comment]
Hi,
problem fixed, it was in db encryption layer. Please update backend to last version - it means run docker-compose pull again ..
Fixed version of shieldoo-mesh-admin is v0.1.6

**Comment by valda-z** [comment]
update backend to 0.1.6

**Comment by valda-z** [comment]
@insta-ruv - please can you confirm that it works now for you?

**Comment by insta-ruv** [comment]
@valda-z 

Hi there,

Thank you very much!

I can indeed confirm the issue is resolved. Works 100%.
I've just confirmed on the Windows and MacOS client.
It's safe to assume the Linux client should also work perfectly fine
