### ISSUE TITLE
Server Aliases added to /etc/hosts

### ISSUE THREAD

**Issue by insta-ruv** [cloudfieldcz/shieldoo-mesh-docs#24]
Hi,

When Shieldoo connects with the client app, I noticed /etc/hosts is updated with hostnames and IP addresses of servers according to their "Name" as set in General tab when creating a new server which is great. It automatically takes care of the manual step involved with having to maintain a hosts file and distribute it across multiple hosts.

In the last step of provisioning a full ZTNA setup for non-public services, DNS resolution is usually a big challenge.
To overcome complicated DNS setups and configuration, I manually added aliases to the /etc/hosts file but perhaps "aliases" can be an added feature.

Feature Request:
Adding custom aliases to servers that would also be added to the /etc/hosts entry for that server.

E.g. adding the following aliases to a Docker server called hq-docker1 would results in a /etc/hosts entry
10.100.100.2 hq-docker1 dockernode1 bitwarden.mydomain.com portainer.mydomain.com

![Screenshot 2023-11-13 at 5 42 50 PM](https://github.com/cloudfieldcz/shieldoo-mesh-docs/assets/142221904/3b59a5d6-430d-4788-87c8-9a1161733952)

After connecting with the Shieldoo client, one would be able to navigate to "portainer.mydomain.com" in a browser and it would resolve to 10.100.100.2.
This would overcome complications of trying to provision, manage and set up a split-DNS server to devices connected to the mesh network or having to manually manage a hosts file.

**Alternatives**

1. Manually creating the extra aliases in /etc/hosts file.
E.g.
10.100.100.2 dockernode1 bitwarden.mydomain.com portainer.mydomain.com
It works but it must be manually managed.
2. Changing the server's name to the portainer.mydomain.com
This works, but is limited to a single FQDN

**Additional context**
In certain cases, some servers host multiple services which is accessible only via a FQDN and routed by a reverse proxy or something like Apache having multiple vhosts.

With multiple aliases added to /etc/hosts, it would take care of a complicated DNS setup to resolve DNS via Shieldoo when connected via the client and resolve DNS using the OS DNS server when not connected.

**Comment by valda-z** [comment]
Interesting idea, we will put it to our roadmap.

**Comment by insta-ruv** [comment]
Oh, wow awesome thank you!
Tested it now and it works perfectly!
Accessing non-publicly exposed docker containers behind a firewall via FQDN with zero extra DNS configuration server or client side
